# Generated by Django 4.2.7 on 2025-08-27 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('image_name', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('cancer', 'Cancer Detected'), ('healthy', 'Healthy')], max_length=10)),
                ('confidence', models.FloatField()),
                ('cancer_probability', models.FloatField()),
                ('healthy_probability', models.FloatField()),
                ('model_used', models.CharField(choices=[('vgg16', 'VGG16'), ('regnet', 'RegNetY-320'), ('ensemble', 'Ensemble (Both Models)')], default='ensemble', max_length=20)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('vgg16_result', models.CharField(blank=True, choices=[('cancer', 'Cancer Detected'), ('healthy', 'Healthy')], max_length=10, null=True)),
                ('vgg16_confidence', models.FloatField(blank=True, null=True)),
                ('regnet_result', models.CharField(blank=True, choices=[('cancer', 'Cancer Detected'), ('healthy', 'Healthy')], max_length=10, null=True)),
                ('regnet_confidence', models.FloatField(blank=True, null=True)),
                ('uncertainty_level', models.CharField(blank=True, max_length=10, null=True)),
                ('disagreement_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection',
                'verbose_name_plural': 'Detections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('dentist', 'Dentist'), ('radiologist', 'Radiologist'), ('researcher', 'Researcher'), ('student', 'Student'), ('other', 'Other')], default='doctor', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_reports', models.BooleanField(default=False)),
                ('preferred_model', models.CharField(choices=[('vgg16', 'VGG16'), ('regnet', 'RegNetY-320'), ('ensemble', 'Ensemble (Both Models)')], default='ensemble', max_length=20)),
                ('total_detections', models.IntegerField(default=0)),
                ('cancer_detections', models.IntegerField(default=0)),
                ('healthy_detections', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('smoking_history', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('family_history', models.BooleanField(default=False)),
                ('previous_lesions', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='detection.detection')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
