# Generated by Django 4.2.7 on 2025-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='cancer_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='healthy_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='result',
            field=models.CharField(blank=True, choices=[('cancer', 'Cancer Detected'), ('healthy', 'Healthy')], max_length=10, null=True),
        ),
    ]
